/*<=========Data understanding=========>=*/

PRAGMA table_info(HR);
/*TOTAL EMPLOYEES*/
SELECT COUNT(DISTINCT EmpID) AS total_employees FROM HR;
/*TOTAL DEPARTMENTS*/
SELECT COUNT(DISTINCT Department) AS total_departments FROM HR;
/*TOTAL JOB ROLES*/
SELECT COUNT(DISTINCT JobRole) AS total_Job_Roles FROM HR;
/*TOTAL EDUCATION FIELDS*/
SELECT COUNT(DISTINCT EducationField) AS total_Education_fields FROM HR;
/*TOTAL BUSINESS TRAVEL TYPES*/
SELECT COUNT(DISTINCT BusinessTravel) AS total_business_travel_types FROM HR;
/*AGE RANGE*/
SELECT CONCAT(MIN(Age)||'-'||MAX(Age)) AS age_range FROM HR;
/*SALARY RANGE*/
SELECT CONCAT(MIN(MonthlyIncome)||'-'||MAX(MonthlyIncome)) AS salary_range FROM HR;
/*YEARS AT COMPANY RANGE*/
SELECT CONCAT(MIN(YearsAtCompany)||'-'||MAX(YearsAtCompany)) AS years_at_company_range FROM HR;


/*<==========DATA QUALITY==========>*/

/*DUPLICATES*/
SELECT EMPID,T_COUNT FROM (SELECT DISTINCT COUNT(EMPID)OVER(PARTITION BY EMPID) AS T_COUNT,EMPID FROM HR)
WHERE T_COUNT>1;
/*NULLS*/
SELECT COUNT(CASE WHEN EMPID IS NULL THEN 1 END) FROM HR;
/*DISTINCT VALUES*/
SELECT COUNT(*) FROM (SELECT DISTINCT * FROM HR);
/*INVALID VALUES*/
SELECT COUNT(CASE WHEN GENDER IN ('Male','Female') THEN 1 END) FROM HR;
/*NEGAIVE SALARY*/
SELECT COUNT(EMPID) FROM HR
WHERE MONTHLYINCOME<=0;
/*IMPOSSIBLE AGE*/
SELECT COUNT(EMPID) FROM HR
WHERE AGE<10 AND AGE>65;


/*<==========EMPLOYEE KPIS==========>*/

/*EMPLOYEE COUNT*/
SELECT COUNT(DISTINCT EMPID) FROM HR;
/*AVERAGE SALARY*/
SELECT ROUND(AVG(MONTHLYINCOME),0) AS AVERAGE_SALARY FROM HR;
/*AVERAGE AGE*/
SELECT ROUND(AVG(AGE),0) AS AVERAGE_AGE FROM HR;
/*AVERAGE YEARS AT COMPANY*/
SELECT ROUND(AVG(YEARSATCOMPANY),0) AS AVG_YEARS_AT_COMPANY FROM HR;
/*AVERAGE HOURLY RATE*/
SELECT ROUND(AVG(HOURLYRATE),0) AS AVG_HOURLY_RATE FROM HR;
/*AVERAGE DAILY RATE*/
SELECT ROUND(AVG(DAILYRATE),0) AS AVG_DAILY_RATE FROM HR;


/*<==========ATTRITION ANALYSIS==========>*/

/*OVERALL ATTRITION %*/
SELECT ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR;
/*ATTRITION BY DEPT*/
SELECT Department, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY Department;

/*ATTRITION BY GENDER*/
SELECT Gender, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY Gender;
/*ATTRITION BY JOB ROLE*/
SELECT JobRole, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY JobRole;
/*ATTRITION BY EDUCATION*/
SELECT EducationField, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY EducationField;
/*ATTRITION BY OVERTIME*/
SELECT OverTime, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY OverTime;
/*ATTRITION BY MARITAL STATUS*/
SELECT MaritalStatus, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY MaritalStatus;
/*ATTRITION BY BUSINESS TRAVEL*/
SELECT BusinessTravel, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY BusinessTravel;
/*ATTRITION BY SALARY BAND*/
SELECT SalarySlab, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY SalarySlab;
/*ATTRITION BY AGE GROUP*/
SELECT AgeGroup, ROUND(
COUNT(CASE WHEN "Attrition"='Yes' THEN 1 END)*100.0/COUNT(*),2
) AS OVERALL_ATT FROM HR
GROUP BY AgeGroup;

/*It can be clearly seen through the data analysis that employees who are young, single, who are in less salaryslab,
travel frequently, and perform overtime especially in human resources, particularly in sales are more prominant to search for better
opportunities. With male leading the attrition by 2%. */


/*<==========SALARY ANALYSIS==========>*/

/*AVG SALARY BY DEPT*/
SELECT Department, ROUND(AVG(MonthlyIncome),0) AS AVG_SALARY FROM HR
GROUP BY Department;
/*HIGHEST SALARY*/
SELECT Department,MAX(MONTHLYINCOME) AS HIGHEST_SALARY FROM HR;
/*LOWEST SALARY*/
SELECT Department,MIN(MONTHLYINCOME) AS LOWEST_SALARY FROM HR;

/*TOP 10 HIGHEST PAID EMPLOYEES*/
SELECT Department,MONTHLYINCOME FROM HR
ORDER BY MONTHLYINCOME DESC
LIMIT 10;
/*SALARY RANKING*/
SELECT * FROM (SELECT Department,MonthlyIncome,
RANK() OVER(ORDER BY MONTHLYINCOME) AS RNK FROM HR
GROUP BY Department)
WHERE RNK<=3;
/*SALARY QUARTILES*/
SELECT * FROM
(SELECT EMPID,DEPARTMENT,NTILE(4) OVER(ORDER BY MonthlyIncome) AS SALARY_QUARTILE FROM HR)
WHERE EMPID='';


/*<===========EXPERIENCE==========>*/

/*AVG YEARS AT COMPANY*/
SELECT ROUND(AVG(YearsAtCompany),0) AS avg_yrsatcom FROM HR;
/*AVG YEARS IN CURRENT ROLE*/
SELECT ROUND(AVG(YearsInCurrentRole),0) AS avg_yrsatcom FROM HR;
/*AVG YEARS SINCE LAST PROMOTION*/
SELECT ROUND(AVG(YearsSinceLastPromotion),0) AS avg_yrsatcom FROM HR;
/*AVG YEARS WITH CURRENT MANAGER*/
SELECT ROUND(AVG(YearsWithCurrManager),0) AS avg_yrsatcom FROM HR;



/*<===========PERFORMANCE==========>*/

/*AVG PERFORMANCE RATING*/
SELECT ROUND(AVG(PerformanceRating),0) AS avg_yrsatcom FROM HR;
/*AVG JOB SATISFACTION*/
SELECT ROUND(AVG(JobSatisfaction),0) AS avg_yrsatcom FROM HR;
/*AVG ENVITONMENT SATISFACTION*/
SELECT ROUND(AVG(EnvironmentSatisfaction),0) AS avg_yrsatcom FROM HR;
/*AVG WORK LIFE BALANCE*/
SELECT ROUND(AVG(WorkLifeBalance),0) AS avg_yrsatcom FROM HR;
/*AVG JOB INVOLVEMENT*/
SELECT ROUND(AVG(JobInvolvement),0) AS avg_yrsatcom FROM HR;
